"use client";

import "./model-viewer";

// ── Typographie ───────────────────────────────────────────────────────────────
export * from "./components/typographie/heading/Heading";
export * from "./components/typographie/text/Text";
export * from "./components/typographie/text/Text.type";
export * from "./components/typographie/text_block/TextBlock";

// ── Carte ─────────────────────────────────────────────────────────────────────
export * from "./components/carte/textcard/TextCard";
export * from "./components/carte/intro_card/IntroCard";
export * from "./components/carte/intro_card/IntroCard.type";
export * from "./components/carte/bento_card/BentoCard";
export * from "./components/carte/bento_card/BentoCard.type";
export * from "./components/carte/social_post_card/SocialPostCard";
export * from "./components/carte/social_post_card/SocialPostCard.type";
export * from "./components/carte/testimonials/Testimonials"
export * from "./components/carte/testimonials/Testimonials.type"
export * from "./components/carte/testimonials/start_rating/StarRating"

// ── Layout ────────────────────────────────────────────────────────────────────
export * from "./components/layout/app_shell/AppShell";
export * from "./components/layout/header_bar/HeaderBar";
export * from "./components/layout/sidebar_nav/SidebarNav";
export * from "./components/layout/sidebar/Sidebar";
export * from "./components/layout/sidebar/Sidebar.type";
export * from "./components/layout/topbar/Topbar";
export * from "./components/layout/topbar/Topbar.type";
export * from "./components/layout/burger_menu/BurgerMenu";
export * from "./components/layout/burger_menu/BurgerMenu.type";
export * from "./components/layout/top_nav/TopNav";
export * from "./components/layout/top_nav/TopNav.type";
export * from "./components/layout/footer_bar/FooterBar";
export * from "./components/layout/bento_grid/BentoGrid";
export * from "./components/layout/bento_grid/BentoGrid.type";

// ── Navigation ────────────────────────────────────────────────────────────────
export * from "./components/navigation/logo_mark/LogoMark";
export * from "./components/navigation/search_bar/SearchBar";
export * from "./components/navigation/search_results/SearchResults";
export * from "./components/navigation/search_results/SearchResults.type";
export * from "./components/navigation/menu_tree/MenuTree";
export * from "./components/navigation/breadcrumb/Breadcrumb";

// ── Catalog / Docs ────────────────────────────────────────────────────────────
export * from "./components/catalog/props_table/PropsTable";
export * from "./components/catalog/props_table/PropsTable.type";
export * from "./components/catalog/code_block/CodeBlock";
export * from "./components/catalog/copy_button/CopyButton";
export * from "./components/catalog/link_list/LinkList";
export * from "./components/catalog/section_gallery/SectionGallery";
export * from "./components/catalog/section_example_card/SectionExampleCard";
export * from "./components/catalog/component_detail_panel/ComponentDetailPanel";
export * from "./components/catalog/component_card/ComponentCard";
export * from "./components/catalog/component_card/ComponentCard.type";
export * from "./components/catalog/doc_page_header/DocPageHeader";
export * from "./components/catalog/doc_page_header/DocPageHeader.type";
export * from "./components/catalog/page_hero/PageHero";
export * from "./components/catalog/page_hero/PageHero.type";

// ── Carrousel ─────────────────────────────────────────────────────────────────
export * from "./components/carrousel/media_carousel/MediaCarousel";

// ── Section ─────────────────────────────────────────────────────────────────
export * from "./components/sections/newsletter/NewsLetter.type"
export * from "./components/sections/newsletter/NewsLetter"

// ── Animation ─────────────────────────────────────────────────────────────────
export * from "./components/animation/marquee/Marquee";
export * from "./components/animation/marquee/Marquee.type";
export * from "./components/animation/animated_list/AnimatedList";
export * from "./components/animation/animated_list/AnimatedList.type";
export * from "./components/animation/animated_stack/AnimatedStack";
export * from "./components/animation/animated_stack/AnimatedStack.type";
export * from "./components/animation/SignatureDetails/SignatureDetails";
export * from "./components/animation/SignatureDetails/SignatureDetails.type";
export * from "./components/animation/NebulaViewer/NebulaViewer";
export * from "./components/animation/NebulaViewer/NebulaViewer.type";

// ── Content ───────────────────────────────────────────────────────────────────
export * from "./components/content/project_description_panel/ProjectDescriptionPanel";

// ── UI Controls ───────────────────────────────────────────────────────────────
export * from "./components/ui/button/Button";
export * from "./components/ui/input/Input";
export * from "./components/ui/select/Select";
export * from "./components/ui/select/Select.type";
export * from "./components/ui/textarea/Textarea";
export * from "./components/ui/tooltip/Tooltip";
export * from "./components/ui/alert/Alert";
export * from "./components/ui/badge/Badge";
export * from "./components/ui/spinner/Spinner";
export * from "./components/ui/checkbox/Checkbox";
export * from "./components/ui/radio/Radio";
export * from "./components/ui/tabs/Tabs";
export * from "./components/ui/accordion/Accordion";
export * from "./components/ui/toggle_switch/ToggleSwitch";
export * from "./components/ui/theme_toggle/ThemeToggle";
export * from "./components/ui/progress_bar/ProgressBar";
export * from "./components/ui/progress_bar/ProgressBar.type";
export * from "./components/ui/callout/Callout";
export * from "./components/ui/callout/Callout.type";
export * from "./components/ui/theme_toggle/ThemeToggle.type";
export * from "./components/ui/tag_chip/TagChip";
export * from "./components/ui/status_label/StatusLabel";
export * from "./components/ui/media_image/MediaImage";
export * from "./components/ui/location_map/LocationMap";
export * from "./components/ui/location_map/LocationMap.type";
export * from "./components/ui/avatar_circles/AvatarCircles";
export * from "./components/ui/avatar_circles/AvatarCircles.type";
export * from "./components/ui/confetti/Confetti";
export * from "./components/ui/confetti/Confetti.type";
export * from "./components/ui/confetti/ConfettiButton";
export * from "./components/ui/confetti/ConfettiButton.type";
export * from "./components/ui/theme_toggle_simple/ThemeToggleSimple";
export * from "./components/ui/theme_toggle_simple/ThemeToggleSimple.type";
export * from "./components/ui/theme_toggler/ThemeToggler";
export * from "./components/ui/theme_toggler/ThemeToggler.type";

// ── Footer ────────────────────────────────────────────────────────────────────
export * from "./components/footer/footer_links/FooterLinks";
export * from "./components/footer/footer_links/FooterLinks.type";
export * from "./components/footer/social_links/SocialLinks";
export * from "./components/footer/social_links/SocialLinks.type";
export * from "./components/footer/footer_contact/FooterContact";
export * from "./components/footer/footer_contact/FooterContact.type";
export * from "./components/footer/footer_legal/FooterLegal";
export * from "./components/footer/footer_legal/FooterLegal.type";
export * from "./components/footer/brand_slogan/BrandSlogan";
export * from "./components/footer/brand_slogan/BrandSlogan.type";

// ── Sections ──────────────────────────────────────────────────────────────────
export * from "./components/sections/hero_cta_section/HeroCtaSection.type";
export * from "./components/sections/hero_cta_section/HeroCtaSection";
export * from "./components/sections/feature_list_section/FeatureListSection";
export * from "./components/sections/section_header/SectionHeader";
export * from "./components/sections/carousel_with_text_section/CarouselWithTextSection";
export * from "./components/sections/component_presentation_section/ComponentPresentationSection";

// ── Backgrounds ───────────────────────────────────────────────────────────────
export * from "./components/background/WarpBackground";
export * from "./components/background/WarpBackground.type";
export * from "./components/background/FlickeringGrid";
export * from "./components/background/FlickeringGrid.type";
export * from "./components/background/AnimatedGridPattern";
export * from "./components/background/AnimatedGridPattern.type";
export * from "./components/background/RetroGrid";
export * from "./components/background/RetroGrid.type";
export * from "./components/background/RippleBackground";
export * from "./components/background/RippleBackground.type";
export * from "./components/background/DotPattern";
export * from "./components/background/DotPattern.type";
export * from "./components/background/GridPattern";
export * from "./components/background/GridPattern.type";
export * from "./components/background/StripedPattern";
export * from "./components/background/StripedPattern.type";
export * from "./components/background/InteractiveGridPattern";
export * from "./components/background/InteractiveGridPattern.type";
export * from "./components/background/LightRaysBackground";
export * from "./components/background/LightRaysBackground.type";
export * from "./components/background/NoiseMeshBackground";
export * from "./components/background/NoiseMeshBackground.type";
export * from "./components/background/GlassAuroraBackground";
export * from "./components/background/GlassAuroraBackground.type";

// ── Animated Text ─────────────────────────────────────────────────────────────
export * from "./components/animated_text/animated_text.types";
export * from "./components/animated_text/text_animate/TextAnimate";
export * from "./components/animated_text/typing_animation/TypingAnimation";
export * from "./components/animated_text/aurora_text/AuroraText";
export * from "./components/animated_text/number_ticker/NumberTicker";
export * from "./components/animated_text/animated_gradient_text/AnimatedGradientText";
export * from "./components/animated_text/text_reveal/TextReveal";
export * from "./components/animated_text/word_rotate/WordRotate";
export * from "./components/animated_text/hyper_text/HyperText";
export * from "./components/animated_text/sparkles_text/SparklesText";
export * from "./components/animated_text/text_highlighter/TextHighlighter";
export * from "./components/animated_text/noise_reveal_text/NoiseRevealText";
export * from "./components/animated_text/variable_font_warp_text/VariableFontWarpText";
export * from "./components/animated_text/variable_font_warp_text/VariableFontWarpText.type";
export * from "./components/animated_text/magnetic_text/MagneticText";
export * from "./components/animated_text/kinetic_underline_text/KineticUnderlineText";
export * from "./components/animated_text/shimmer_border_text/ShimmerBorderText";
export * from "./components/animated_text/glow_pulse_text/GlowPulseText";
export * from "./components/animated_text/segment_emphasis_text/SegmentEmphasisText";
export * from "./components/animated_text/segment_emphasis_text/SegmentEmphasisText.type";
export * from "./components/animated_text/progressive_blur_text/ProgressiveBlurText";

// ── Quiz ──────────────────────────────────────────────────────────────────────
export * from "./components/quiz/quiz.types";
export * from "./components/quiz/quiz_section/QuizSection";
export * from "./components/quiz/quiz_section/QuizSection.type";
export * from "./components/quiz/question_card/QuestionCard";
export * from "./components/quiz/question_card/QuestionCard.type";
export * from "./components/quiz/question_renderer/QuestionRenderer";
export * from "./components/quiz/question_renderer/QuestionRenderer.type";
export * from "./components/quiz/conditional_logic/ConditionalLogic";
export * from "./components/quiz/conditional_logic/ConditionalLogic.type";
export * from "./components/quiz/quiz_builder/QuizBuilder";
export * from "./components/quiz/quiz_builder/QuizBuilder.type";
export * from "./components/quiz/single_choice/SingleChoice";
export * from "./components/quiz/single_choice/SingleChoice.type";
export * from "./components/quiz/multi_choice/MultiChoice";
export * from "./components/quiz/multi_choice/MultiChoice.type";
export * from "./components/quiz/scale_likert/ScaleLikert";
export * from "./components/quiz/scale_likert/ScaleLikert.type";
export * from "./components/quiz/rating_stars/RatingStars";
export * from "./components/quiz/rating_stars/RatingStars.type";
export * from "./components/quiz/nps_question/NPSQuestion";
export * from "./components/quiz/nps_question/NPSQuestion.type";
export * from "./components/quiz/range_slider_question/RangeSliderQuestion";
export * from "./components/quiz/range_slider_question/RangeSliderQuestion.type";
export * from "./components/quiz/free_text_question/FreeTextQuestion";
export * from "./components/quiz/free_text_question/FreeTextQuestion.type";
export * from "./components/quiz/matrix_question/MatrixQuestion";
export * from "./components/quiz/matrix_question/MatrixQuestion.type";
export * from "./components/quiz/rank_order_question/RankOrderQuestion";
export * from "./components/quiz/rank_order_question/RankOrderQuestion.type";
export * from "./components/quiz/quiz_progress/QuizProgress";
export * from "./components/quiz/quiz_progress/QuizProgress.type";
export * from "./components/quiz/quiz_timer/QuizTimer";
export * from "./components/quiz/quiz_timer/QuizTimer.type";
export * from "./components/quiz/quiz_navigation/QuizNavigation";
export * from "./components/quiz/quiz_navigation/QuizNavigation.type";
export * from "./components/quiz/quiz_submit_bar/QuizSubmitBar";
export * from "./components/quiz/quiz_submit_bar/QuizSubmitBar.type";
export * from "./components/quiz/quiz_result_summary/QuizResultSummary";
export * from "./components/quiz/quiz_result_summary/QuizResultSummary.type";
export * from "./components/quiz/answer_review/AnswerReview";
export * from "./components/quiz/answer_review/AnswerReview.type";
export * from "./components/quiz/response_table/ResponseTable";
export * from "./components/quiz/response_table/ResponseTable.type";

// ── Analytics ─────────────────────────────────────────────────────────────────
export * from "./components/analytics/analytics.types";
export * from "./components/analytics/insight_cards/InsightCards";
export * from "./components/analytics/insight_cards/InsightCards.type";
export * from "./components/analytics/survey_funnel/SurveyFunnel";
export * from "./components/analytics/survey_funnel/SurveyFunnel.type";
export * from "./components/analytics/distribution_chart/DistributionChart";
export * from "./components/analytics/distribution_chart/DistributionChart.type";
export * from "./components/analytics/heatmap_matrix/HeatmapMatrix";
export * from "./components/analytics/heatmap_matrix/HeatmapMatrix.type";
export * from "./components/analytics/cohort_trends/CohortTrends";
export * from "./components/analytics/cohort_trends/CohortTrends.type";
export * from "./components/analytics/segment_filter_bar/SegmentFilterBar";
export * from "./components/analytics/segment_filter_bar/SegmentFilterBar.type";
export * from "./components/analytics/dashboard_grid/DashboardGrid";
export * from "./components/analytics/dashboard_grid/DashboardGrid.type";
export * from "./components/analytics/kpi_trend_widget/KPITrendWidget";
export * from "./components/analytics/kpi_trend_widget/KPITrendWidget.type";
export * from "./components/analytics/anomaly_badge/AnomalyBadge";
export * from "./components/analytics/anomaly_badge/AnomalyBadge.type";
export * from "./components/analytics/drilldown_panel/DrilldownPanel";
export * from "./components/analytics/drilldown_panel/DrilldownPanel.type";

// ── Misc ──────────────────────────────────────────────────────────────────────
export * from "./components/HelloBrickslab";

// ── Dashboard ────────────────────────────────────────────────────────────────
export * from "./components/dashboard/ComponentsCountCard";
export * from "./components/dashboard/ComponentsCountCard.type";
export * from "./components/dashboard/KpiCard";
export * from "./components/dashboard/KpiCard.type";
export * from "./components/dashboard/LatestComponentsList";
export * from "./components/dashboard/LatestComponentsList.type";
export * from "./components/dashboard/TestResultsCard";
export * from "./components/dashboard/TestResultsCard.type";
export * from "./components/dashboard/DashboardHero";
export * from "./components/dashboard/DashboardHero.type";
