// Données des composants pour la recherche et la navigation avec descriptions
// [AUTO-GENERATED] Synchronized from components.csv
export interface ComponentData {
  label: string;
  href: string;
  section: string;
  type: "web" | "mobile";
  description: string;
  addedAt?: string;
}

export const componentsData: ComponentData[] = [
  {
    label: "NewsLetter",
    href: "/components/newsletter",
    section: "Sections",
    type: "web" as const,
    description: "NewsLetter section",
    addedAt: "2026-03-17",
  },
  {
    label: "Testimonial",
    href: "/components/testimonials",
    section: "Cards",
    type: "web" as const,
    description: "Card component for testimonials",
    addedAt: "2026-03-17",
  },
  {
    label: "StarRating",
    href: "/components/starrating",
    section: "Cards",
    type: "web" as const,
    description: "Read-only star rating display with support for half values and configurable icon size",
    addedAt: "2026-03-18",
  },
  {
    label: "AppShell",
    href: "/components/appshell",
    section: "Layout & Shell",
    type: "web" as const,
    description: "Container component for page layout with header sidebar and footer",
  },
  {
    label: "HeaderBar",
    href: "/components/headerbar",
    section: "Layout & Shell",
    type: "web" as const,
    description: "Top navigation and branding header component",
  },
  {
    label: "FooterBar",
    href: "/components/footerbar",
    section: "Layout & Shell",
    type: "web" as const,
    description: "Footer with links branding and social media",
  },
  {
    label: "SidebarNav",
    href: "/components/sidebarnav",
    section: "Layout & Shell",
    type: "web" as const,
    description: "Vertical navigation sidebar for main menu",
  },
  {
    label: "BurgerMenu",
    href: "/components/burgermenu",
    section: "Layout & Shell",
    type: "web" as const,
    description: "Mobile hamburger menu with overlay navigation",
  },
  {
    label: "TopNav",
    href: "/components/topnav",
    section: "Layout & Shell",
    type: "web" as const,
    description: "Alternative top navigation component",
  },
  {
    label: "BentoGrid",
    href: "/components/bentogrid",
    section: "Layout & Shell",
    type: "web" as const,
    description: "Responsive bento grid layout with auto-fit dense mode and customizable columns",
    addedAt: "2026-03-05",
  },
  {
    label: "LogoMark",
    href: "/components/logomark",
    section: "Navigation",
    type: "web" as const,
    description: "Brand logo mark component",
  },
  {
    label: "SearchBar",
    href: "/components/searchbar",
    section: "Navigation",
    type: "web" as const,
    description: "Input field for searching and filtering",
  },
  {
    label: "MenuTree",
    href: "/components/menutree",
    section: "Navigation",
    type: "web" as const,
    description: "Hierarchical menu with expandable items",
  },
  {
    label: "Breadcrumb",
    href: "/components/breadcrumb",
    section: "Navigation",
    type: "web" as const,
    description: "Navigation trail component showing page hierarchy",
  },
  {
    label: "MediaCarousel",
    href: "/components/mediacarousel",
    section: "Carousel",
    type: "web" as const,
    description: "Carousel for displaying images and media with autoplay",
  },
  {
    label: "Marquee",
    href: "/components/marquee",
    section: "Animation",
    type: "web" as const,
    description: "Infinite horizontal or vertical scroll with pause on hover and reverse direction",
    addedAt: "2026-03-05",
  },
  {
    label: "AnimatedList",
    href: "/components/animatedlist",
    section: "Animation",
    type: "web" as const,
    description: "List with staggered sequential item animations and loop support",
    addedAt: "2026-03-05",
  },
  {
    label: "AnimatedStack",
    href: "/components/animatedstack",
    section: "Animation",
    type: "web" as const,
    description: "Notification stack with card pile effect — new items pop from top with bounce and stack behind",
    addedAt: "2026-03-06",
  },
  {
    label: "SignatureDetails",
    href: "/components/signaturedetails",
    section: "Animation",
    type: "web" as const,
    description: "Signature grid with hover overlay reveal image zoom and configurable columns",
    addedAt: "2026-03-16",
  },
  {
    label: "NebulaViewer",
    href: "/components/nebulaviewer",
    section: "Animation",
    type: "web" as const,
    description: "3D viewer based on <model-viewer> with halo glow model switcher and rotation toggle",
    addedAt: "2026-03-16",
  },
  {
    label: "Heading",
    href: "/components/heading",
    section: "Typography",
    type: "web" as const,
    description: "Text heading component with multiple levels",
  },
  {
    label: "Text",
    href: "/components/text",
    section: "Typography",
    type: "web" as const,
    description: "Body text and paragraph component",
  },
  {
    label: "TextBlock",
    href: "/components/textblock",
    section: "Typography",
    type: "web" as const,
    description: "Multi-line text content block",
  },
  {
    label: "Button",
    href: "/components/button",
    section: "UI Controls",
    type: "web" as const,
    description: "Versatile action button with 4 variants sizes icons and loading state",
  },
  {
    label: "Input",
    href: "/components/input",
    section: "UI Controls",
    type: "web" as const,
    description: "Controlled text input with label helper error icons and 3 sizes",
  },
  {
    label: "Select",
    href: "/components/select",
    section: "UI Controls",
    type: "web" as const,
    description: "Controlled native select with label helper error states and 3 sizes",
  },
  {
    label: "Textarea",
    href: "/components/textarea",
    section: "UI Controls",
    type: "web" as const,
    description: "Controlled multi-line text area with label helper error counter and autoResize",
  },
  {
    label: "TagChip",
    href: "/components/tagchip",
    section: "UI Controls",
    type: "web" as const,
    description: "Small label or tag component with removable option",
  },
  {
    label: "StatusLabel",
    href: "/components/statuslabel",
    section: "UI Controls",
    type: "web" as const,
    description: "Badge showing component or feature status",
  },
  {
    label: "ToggleSwitch",
    href: "/components/toggle",
    section: "UI Controls",
    type: "web" as const,
    description: "Binary switch component for on/off states",
  },
  {
    label: "AvatarCircles",
    href: "/components/avatarcircles",
    section: "UI Controls",
    type: "web" as const,
    description: "Stacked avatar circles with overlap and counter badge",
    addedAt: "2026-03-05",
  },
  {
    label: "Confetti",
    href: "/components/confetti",
    section: "UI Controls",
    type: "web" as const,
    description: "Canvas-based confetti animation effect with customizable particles",
    addedAt: "2026-03-05",
  },
  {
    label: "ConfettiButton",
    href: "/components/confettibutton",
    section: "UI Controls",
    type: "web" as const,
    description: "Button that triggers confetti animation on click",
    addedAt: "2026-03-05",
  },
  {
    label: "ThemeToggler",
    href: "/components/themetoggler",
    section: "UI Controls",
    type: "web" as const,
    description: "Theme toggle with animated transition between light dark and system modes",
    addedAt: "2026-03-05",
  },
  {
    label: "ThemeToggleSimple",
    href: "/components/themetogglesimple",
    section: "UI Controls",
    type: "web" as const,
    description: "Simple theme toggle without animations for accessibility",
    addedAt: "2026-03-05",
  },
  {
    label: "MediaImage",
    href: "/components/mediaimage",
    section: "UI Controls",
    type: "web" as const,
    description: "Responsive image component with lazy loading",
  },
  {
    label: "LocationMap",
    href: "/components/locationmap",
    section: "UI Controls",
    type: "web" as const,
    description: "Map component for displaying a place location with coordinates and OpenStreetMap embed",
    addedAt: "2026-03-06",
  },
  {
    label: "CopyButton",
    href: "/components/copybutton",
    section: "UI Controls",
    type: "web" as const,
    description: "Button that copies content to clipboard",
  },
  {
    label: "IntroCard",
    href: "/components/introcard",
    section: "Cards",
    type: "web" as const,
    description: "Hero/intro card component with gradient background and CTA",
  },
  {
    label: "TextCard",
    href: "/components/textcard",
    section: "Cards",
    type: "web" as const,
    description: "Card component displaying text content",
  },
  {
    label: "BentoCard",
    href: "/components/bentocard",
    section: "Cards",
    type: "web" as const,
    description: "Feature card for bento grid with icon title description and hover effects",
    addedAt: "2026-03-05",
  },
  {
    label: "SocialPostCard",
    href: "/components/socialpostcard",
    section: "Cards",
    type: "web" as const,
    description: "Data-driven social post card supporting X LinkedIn and custom platforms with metrics",
    addedAt: "2026-03-05",
  },
  {
    label: "SectionExampleCard",
    href: "/components/sectionexamplecard",
    section: "Cards",
    type: "web" as const,
    description: "Card showcasing component examples",
  },
  {
    label: "SectionGallery",
    href: "/components/sectiongallery",
    section: "Sections",
    type: "web" as const,
    description: "Gallery layout for showcasing multiple items",
  },
  {
    label: "SectionHeader",
    href: "/components/sectionheader",
    section: "Sections",
    type: "web" as const,
    description: "Header section for page introductions",
  },
  {
    label: "HeroCTASection",
    href: "/components/heroctasection",
    section: "Sections",
    type: "web" as const,
    description: "Large hero banner with call-to-action",
  },
  {
    label: "FeatureListSection",
    href: "/components/featurelistsection",
    section: "Sections",
    type: "web" as const,
    description: "Section displaying feature list items",
  },
  {
    label: "CarouselWithTextSection",
    href: "/components/carouselwithtextsection",
    section: "Sections",
    type: "web" as const,
    description: "Section combining carousel with text content",
  },
  {
    label: "BrandSlogan",
    href: "/components/brandslogan",
    section: "Branding",
    type: "web" as const,
    description: "Brand tagline and slogan display",
  },
  {
    label: "SocialLinks",
    href: "/components/sociallinks",
    section: "Footer",
    type: "web" as const,
    description: "Social media link list component",
  },
  {
    label: "FooterLinks",
    href: "/components/footerlinks",
    section: "Footer",
    type: "web" as const,
    description: "Navigation links in footer",
  },
  {
    label: "FooterLegal",
    href: "/components/footerlegal",
    section: "Footer",
    type: "web" as const,
    description: "Legal information section in footer",
  },
  {
    label: "FooterContact",
    href: "/components/footercontact",
    section: "Footer",
    type: "web" as const,
    description: "Contact information in footer",
  },
  {
    label: "LinkList",
    href: "/components/linklist",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "List of links with optional descriptions for navigation or index sections",
  },
  {
    label: "CodeBlock",
    href: "/components/codeblock",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Syntax-highlighted code display component",
  },
  {
    label: "ComponentDetailPanel",
    href: "/components/componentdetailpanel",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Details panel for component documentation",
  },
  {
    label: "ComponentPresentationSection",
    href: "/components/componentpresentationsection",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Section for presenting component variations",
  },
  {
    label: "PropsTable",
    href: "/components/propstable",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Table showing component props and their types",
  },
  {
    label: "ProjectDescriptionPanel",
    href: "/components/projectdescriptionpanel",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Panel with project description and details",
  },
  {
    label: "ComponentCard",
    href: "/components/componentcard",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Catalog card presenting a component with name section description platform badge and optional live preview",
  },
  {
    label: "DocPageHeader",
    href: "/components/docpageheader",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Standard header for component documentation pages with name h1 description package badge and extra badges",
  },
  {
    label: "PageHero",
    href: "/components/pagehero",
    section: "Catalog/Docs",
    type: "web" as const,
    description: "Full-width page hero with gradient mesh dot grid eyebrow stats row — replaces SectionHeader for main nav pages",
    addedAt: "2026-03-05",
  },
  {
    label: "Topbar",
    href: "/components/topbar",
    section: "Catalog/App",
    type: "web" as const,
    description: "Navigation bar with logo search and mobile menu",
  },
  {
    label: "Sidebar",
    href: "/components/sidebar",
    section: "Catalog/App",
    type: "web" as const,
    description: "Desktop navigation sidebar with component sections",
  },
  {
    label: "SearchResults",
    href: "/components/searchresults",
    section: "Catalog/App",
    type: "web" as const,
    description: "Search results dropdown component",
  },
  {
    label: "ThemeToggle",
    href: "/components/themetoggle",
    section: "Catalog/App",
    type: "web" as const,
    description: "Interrupteur thème sombre/clair",
  },
  {
    label: "ComponentsCountCard",
    href: "/components/componentscountcard",
    section: "Dashboard",
    type: "web" as const,
    description: "Card showing the total number of catalogued components",
  },
  {
    label: "LatestComponentsList",
    href: "/components/latestcomponentslist",
    section: "Dashboard",
    type: "web" as const,
    description: "List of the most recently added components",
  },
  {
    label: "TestResultsCard",
    href: "/components/testresultscard",
    section: "Dashboard",
    type: "web" as const,
    description: "Card summarizing automated test pass rates by component",
  },
  {
    label: "KpiCard",
    href: "/components/kpicard",
    section: "Dashboard",
    type: "web" as const,
    description: "Small card displaying a key performance indicator with label value and helper",
    addedAt: "2026-03-05",
  },
  {
    label: "DashboardHero",
    href: "/components/dashboardhero",
    section: "Dashboard",
    type: "web" as const,
    description: "Hero section for the dashboard with CTA and design system overview",
    addedAt: "2026-03-05",
  },
  {
    label: "QuizBuilder",
    href: "/components/quizbuilder",
    section: "Quiz",
    type: "web" as const,
    description: "Visual quiz editor with builder preview and split modes — manages sections questions and autosave",
    addedAt: "2026-03-06",
  },
  {
    label: "QuizSection",
    href: "/components/quizsection",
    section: "Quiz",
    type: "web" as const,
    description: "Collapsible section container for quiz questions with title description and helper text",
    addedAt: "2026-03-06",
  },
  {
    label: "QuestionCard",
    href: "/components/questioncard",
    section: "Quiz",
    type: "web" as const,
    description: "Standardized question wrapper with label required indicator points status error and hint",
    addedAt: "2026-03-06",
  },
  {
    label: "QuestionRenderer",
    href: "/components/questionrenderer",
    section: "Quiz",
    type: "web" as const,
    description: "Dynamic question renderer dispatching to the correct input component based on question type",
    addedAt: "2026-03-06",
  },
  {
    label: "ConditionalLogic",
    href: "/components/conditionallogic",
    section: "Quiz",
    type: "web" as const,
    description: "Visual rule editor for IF-condition THEN-action quiz branching and scoring logic",
    addedAt: "2026-03-06",
  },
  {
    label: "SingleChoice",
    href: "/components/singlechoice",
    section: "Quiz",
    type: "web" as const,
    description: "Single-select question with radio or card variant and optional free-text other option",
    addedAt: "2026-03-06",
  },
  {
    label: "MultiChoice",
    href: "/components/multichoice",
    section: "Quiz",
    type: "web" as const,
    description: "Multi-select question with checkbox or tag variant and configurable min/max selection",
    addedAt: "2026-03-06",
  },
  {
    label: "ScaleLikert",
    href: "/components/scalelikert",
    section: "Quiz",
    type: "web" as const,
    description: "Likert scale from 1-5 to 1-10 with optional tick bar and extreme labels",
    addedAt: "2026-03-06",
  },
  {
    label: "RatingStars",
    href: "/components/ratingstars",
    section: "Quiz",
    type: "web" as const,
    description: "Star heart or bolt icon rating with optional half-point precision and hover preview",
    addedAt: "2026-03-06",
  },
  {
    label: "NPSQuestion",
    href: "/components/npsquestion",
    section: "Quiz",
    type: "web" as const,
    description: "Net Promoter Score 0-10 selector with detractor passive promoter color zones",
    addedAt: "2026-03-06",
  },
  {
    label: "RangeSliderQuestion",
    href: "/components/rangesliderquestion",
    section: "Quiz",
    type: "web" as const,
    description: "Single or dual-handle range slider with value display and unit label",
    addedAt: "2026-03-06",
  },
  {
    label: "FreeTextQuestion",
    href: "/components/freetextquestion",
    section: "Quiz",
    type: "web" as const,
    description: "Single-line or multiline text input with character counter and min/max length validation",
    addedAt: "2026-03-06",
  },
  {
    label: "MatrixQuestion",
    href: "/components/matrixquestion",
    section: "Quiz",
    type: "web" as const,
    description: "Rows x columns matrix for Likert multi-item grids with single or multi selection per row",
    addedAt: "2026-03-06",
  },
  {
    label: "RankOrderQuestion",
    href: "/components/rankorderquestion",
    section: "Quiz",
    type: "web" as const,
    description: "Drag-and-drop rank ordering list with arrow fallback and position badges",
    addedAt: "2026-03-06",
  },
  {
    label: "QuizProgress",
    href: "/components/quizprogress",
    section: "Quiz",
    type: "web" as const,
    description: "Quiz progress indicator with bar steps and ring modes and optional label",
    addedAt: "2026-03-06",
  },
  {
    label: "QuizTimer",
    href: "/components/quiztimer",
    section: "Quiz",
    type: "web" as const,
    description: "Countdown timer with warn and expire states and optional auto-submit callback",
    addedAt: "2026-03-06",
  },
  {
    label: "QuizNavigation",
    href: "/components/quiznavigation",
    section: "Quiz",
    type: "web" as const,
    description: "Previous Next navigation bar with optional summary panel and jump-to support",
    addedAt: "2026-03-06",
  },
  {
    label: "QuizSubmitBar",
    href: "/components/quizsubmitbar",
    section: "Quiz",
    type: "web" as const,
    description: "Sticky submission bar with save-draft submit and reset actions and loading states",
    addedAt: "2026-03-06",
  },
  {
    label: "QuizResultSummary",
    href: "/components/quizresultsummary",
    section: "Quiz",
    type: "web" as const,
    description: "Post-quiz result card with score ring badges and recommendations in compact or detailed mode",
    addedAt: "2026-03-06",
  },
  {
    label: "AnswerReview",
    href: "/components/answerreview",
    section: "Quiz",
    type: "web" as const,
    description: "Question-by-question answer review with correct/incorrect feedback and correction display",
    addedAt: "2026-03-06",
  },
  {
    label: "ResponseTable",
    href: "/components/responsetable",
    section: "Quiz",
    type: "web" as const,
    description: "Admin response table with client-side sort filter pagination and CSV/XLSX export",
    addedAt: "2026-03-06",
  },
  {
    label: "InsightCards",
    href: "/components/insightcards",
    section: "Analytics",
    type: "web" as const,
    description: "Survey KPI cards grid with trend arrow delta badge and solid or glass variant",
    addedAt: "2026-03-06",
  },
  {
    label: "SurveyFunnel",
    href: "/components/surveyfunnel",
    section: "Analytics",
    type: "web" as const,
    description: "Start-to-complete funnel with bar and step modes drop-off labels and completion rates",
    addedAt: "2026-03-06",
  },
  {
    label: "DistributionChart",
    href: "/components/distributionchart",
    section: "Analytics",
    type: "web" as const,
    description: "Horizontal bar chart with single bar stacked series and histogram modes",
    addedAt: "2026-03-06",
  },
  {
    label: "HeatmapMatrix",
    href: "/components/heatmapmatrix",
    section: "Analytics",
    type: "web" as const,
    description: "Color-intensity matrix for aggregated Likert or cross-tab data with optional scale legend",
    addedAt: "2026-03-06",
  },
  {
    label: "CohortTrends",
    href: "/components/cohorttrends",
    section: "Analytics",
    type: "web" as const,
    description: "Multi-series SVG line chart with axis labels data point tooltips and legend",
    addedAt: "2026-03-06",
  },
  {
    label: "SegmentFilterBar",
    href: "/components/segmentfilterbar",
    section: "Analytics",
    type: "web" as const,
    description: "Dashboard filter bar with text select date and tag fields presets and clear all",
    addedAt: "2026-03-06",
  },
  {
    label: "DashboardGrid",
    href: "/components/dashboardgrid",
    section: "Analytics",
    type: "web" as const,
    description: "Responsive CSS grid layout for widgets with optional drag-and-drop reorder in edit mode",
    addedAt: "2026-03-06",
  },
  {
    label: "KPITrendWidget",
    href: "/components/kpitrendwidget",
    section: "Analytics",
    type: "web" as const,
    description: "KPI card with SVG sparkline delta badge target progress bar and loading skeleton",
    addedAt: "2026-03-06",
  },
  {
    label: "AnomalyBadge",
    href: "/components/anomalybadge",
    section: "Analytics",
    type: "web" as const,
    description: "Pulsing anomaly indicator badge with info warn and critical severity levels",
    addedAt: "2026-03-06",
  },
  {
    label: "DrilldownPanel",
    href: "/components/drilldownpanel",
    section: "Analytics",
    type: "web" as const,
    description: "Slide-in side panel for chart drilldown details with overlay and keyboard close",
    addedAt: "2026-03-06",
  },
  {
    label: "Tooltip",
    href: "/components/tooltip",
    section: "UI Controls",
    type: "web" as const,
    description: "Contextual help bubble with CSS-only hover behavior and 4 positions",
  },
  {
    label: "Alert",
    href: "/components/alert",
    section: "UI Controls",
    type: "web" as const,
    description: "Contextual feedback component with 4 variants info success warning error and optional dismiss",
  },
  {
    label: "Badge",
    href: "/components/badge",
    section: "UI Controls",
    type: "web" as const,
    description: "Compact non-interactive indicator for statuses counts and labels with dot and outlined modes",
  },
  {
    label: "ProgressBar",
    href: "/components/progressbar",
    section: "UI Controls",
    type: "web" as const,
    description: "Horizontal progress bar with 4 color schemes 2 sizes label and animated fill",
  },
  {
    label: "Callout",
    href: "/components/callout",
    section: "UI Controls",
    type: "web" as const,
    description: "Inline contextual message block for documentation with 4 variants and automatic icon and title",
  },
  {
    label: "Spinner",
    href: "/components/spinner",
    section: "UI Controls",
    type: "web" as const,
    description: "CSS-only loading indicator with 6 color variants 4 sizes and 3 speeds via keyframe animation",
  },
  {
    label: "Checkbox",
    href: "/components/checkbox",
    section: "UI Controls",
    type: "web" as const,
    description: "Styled checkbox with appearance:none SVG checkmark controlled state and 3 sizes",
  },
  {
    label: "Radio",
    href: "/components/radio",
    section: "UI Controls",
    type: "web" as const,
    description: "Styled radio button with RadioGroup wrapper for controlled selection vertical and horizontal layouts",
  },
  {
    label: "Tabs",
    href: "/components/tabs",
    section: "UI Controls",
    type: "web" as const,
    description: "Controlled tab navigation with underline pills and boxed variants TabPanel content wrapper and icon support",
  },
  {
    label: "Accordion",
    href: "/components/accordion",
    section: "UI Controls",
    type: "web" as const,
    description: "Disclosure component based on native details/summary with controlled mode 3 variants and fade animation",
  },
  {
    label: "TextAnimate",
    href: "/components/textanimate",
    section: "Animated Text",
    type: "web" as const,
    description: "Multi-segment text animation with presets fade blur slide scale rise by word char or line with viewport trigger and stagger",
  },
  {
    label: "TypingAnimation",
    href: "/components/typinganimation",
    section: "Animated Text",
    type: "web" as const,
    description: "Typewriter effect with single text or word sequence cursor variants loop and delete speed control",
  },
  {
    label: "AuroraText",
    href: "/components/auroratext",
    section: "Animated Text",
    type: "web" as const,
    description: "Moving aurora gradient applied to text via background-clip with configurable colors speed and blend mode",
  },
  {
    label: "NumberTicker",
    href: "/components/numberticker",
    section: "Animated Text",
    type: "web" as const,
    description: "Animated number counter with locale formatting prefix suffix separator and easing from start to target value",
  },
  {
    label: "AnimatedGradientText",
    href: "/components/animatedgradienttext",
    section: "Animated Text",
    type: "web" as const,
    description: "Animated gradient applied to text with shift rotate or pulse modes and linear or radial gradient support",
  },
  {
    label: "TextReveal",
    href: "/components/textreveal",
    section: "Animated Text",
    type: "web" as const,
    description: "Progressive scroll-driven text reveal by word character or line with fade and blur options",
  },
  {
    label: "WordRotate",
    href: "/components/wordrotate",
    section: "Animated Text",
    type: "web" as const,
    description: "Dynamic headline word rotation with slide fade or flip transitions pause on hover and loop support",
  },
  {
    label: "HyperText",
    href: "/components/hypertext",
    section: "Animated Text",
    type: "web" as const,
    description: "Character scramble effect triggered by hover tap auto or viewport with configurable character set and duration",
  },
  {
    label: "SparklesText",
    href: "/components/sparklestext",
    section: "Animated Text",
    type: "web" as const,
    description: "Floating sparkle particles around text with configurable count size speed and colors",
  },
  {
    label: "TextHighlighter",
    href: "/components/texthighlighter",
    section: "Animated Text",
    type: "web" as const,
    description: "SVG animated highlight underline box circle or strike overlay with hover view or manual trigger",
  },
  {
    label: "NoiseRevealText",
    href: "/components/noiserevealtext",
    section: "Animated Text",
    type: "web" as const,
    description: "Cinematic noise-filter reveal using SVG feTurbulence and feDisplacementMap with directional clip animation",
  },
  {
    label: "VariableFontWarpText",
    href: "/components/variablefontwarptext",
    section: "Animated Text",
    type: "web" as const,
    description: "Variable font axis animation on wght wdth slnt triggered by hover scroll or viewport",
  },
  {
    label: "MagneticText",
    href: "/components/magnetictext",
    section: "Animated Text",
    type: "web" as const,
    description: "Magnetic parallax text that follows the cursor within a configurable radius with friction and strength",
  },
  {
    label: "KineticUnderlineText",
    href: "/components/kineticunderlinetext",
    section: "Animated Text",
    type: "web" as const,
    description: "Kinetic underline that expands from center on hover focus or active with configurable thickness and easing",
  },
  {
    label: "ShimmerBorderText",
    href: "/components/shimmerbordertext",
    section: "Animated Text",
    type: "web" as const,
    description: "Text stroke outline with animated shimmer highlight in solid or transparent fill mode",
  },
  {
    label: "GlowPulseText",
    href: "/components/glowpulsetext",
    section: "Animated Text",
    type: "web" as const,
    description: "Pulsing text glow via text-shadow animation triggered always on hover or on viewport entry",
  },
  {
    label: "SegmentEmphasisText",
    href: "/components/segmentemphasistext",
    section: "Animated Text",
    type: "web" as const,
    description: "Intelligent text segment highlighting with raise glow underline or gradient effects on matched words",
  },
  {
    label: "ProgressiveBlurText",
    href: "/components/progressiveblurtext",
    section: "Animated Text",
    type: "web" as const,
    description: "Word-by-word blur-to-clear reveal triggered on scroll or viewport with staggered transitions",
  },
  {
    label: "WarpBackground",
    href: "/components/warpbackground",
    section: "Backgrounds",
    type: "web" as const,
    description: "Animated skew and scale distortion effect with optional radial gradient mask",
    addedAt: "2026-03-05",
  },
  {
    label: "FlickeringGrid",
    href: "/components/flickeringgrid",
    section: "Backgrounds",
    type: "web" as const,
    description: "SVG grid cells with flicker animation and customizable cell size and color",
    addedAt: "2026-03-05",
  },
  {
    label: "AnimatedGridPattern",
    href: "/components/animatedgridpattern",
    section: "Backgrounds",
    type: "web" as const,
    description: "Grid lines moving downward creating a continuous flow effect",
    addedAt: "2026-03-05",
  },
  {
    label: "RetroGrid",
    href: "/components/retrogrid",
    section: "Backgrounds",
    type: "web" as const,
    description: "Perspective 3D synthwave-style grid with perspective zoom animation and optional glow",
    addedAt: "2026-03-05",
  },
  {
    label: "RippleBackground",
    href: "/components/ripplebackground",
    section: "Backgrounds",
    type: "web" as const,
    description: "Concentric ripple rings expanding from center with customizable frequency and amplitude",
    addedAt: "2026-03-05",
  },
  {
    label: "DotPattern",
    href: "/components/dotpattern",
    section: "Backgrounds",
    type: "web" as const,
    description: "Static SVG dot matrix pattern with configurable dot size gap and opacity",
    addedAt: "2026-03-05",
  },
  {
    label: "GridPattern",
    href: "/components/gridpattern",
    section: "Backgrounds",
    type: "web" as const,
    description: "Static SVG grid lines with solid or dashed variants and optional radial mask",
    addedAt: "2026-03-05",
  },
  {
    label: "StripedPattern",
    href: "/components/stripedpattern",
    section: "Backgrounds",
    type: "web" as const,
    description: "Diagonal stripes with optional scroll animation and customizable angle and width",
    addedAt: "2026-03-05",
  },
  {
    label: "InteractiveGridPattern",
    href: "/components/interactivegridpattern",
    section: "Backgrounds",
    type: "web" as const,
    description: "Canvas-based mouse-responsive grid heat effect with customizable cell size and influence radius",
    addedAt: "2026-03-05",
  },
  {
    label: "LightRaysBackground",
    href: "/components/lightraysbackground",
    section: "Backgrounds",
    type: "web" as const,
    description: "God rays light beams flowing downward with configurable ray count speed and opacity",
    addedAt: "2026-03-05",
  },
  {
    label: "NoiseMeshBackground",
    href: "/components/noisemeshbackground",
    section: "Backgrounds",
    type: "web" as const,
    description: "Gradient mesh with subtle noise and grain texture effect using canvas",
    addedAt: "2026-03-05",
  },
  {
    label: "GlassAuroraBackground",
    href: "/components/glassaurorabackground",
    section: "Backgrounds",
    type: "web" as const,
    description: "Glassmorphism with animated aurora gradient effect and backdrop blur",
    addedAt: "2026-03-05",
  },
  {
    label: "ButtonMobile",
    href: "/mobile/button",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile button component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "InputMobile",
    href: "/mobile/input",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile input component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "CheckboxMobile",
    href: "/mobile/checkbox",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile checkbox component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "RadioMobile",
    href: "/mobile/radio",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile radio group component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "ToggleSwitchMobile",
    href: "/mobile/toggle-switch",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile toggle switch component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "BadgeMobile",
    href: "/mobile/badge",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile badge component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "TabsMobile",
    href: "/mobile/tabs",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile tabs component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "AlertMobile",
    href: "/mobile/alert",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile alert component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "ProgressBarMobile",
    href: "/mobile/progress-bar",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile progress bar component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "SpinnerMobile",
    href: "/mobile/spinner",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile spinner component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "SelectMobile",
    href: "/mobile/select",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile select component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "TextareaMobile",
    href: "/mobile/textarea",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile textarea component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "AccordionMobile",
    href: "/mobile/accordion",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile accordion component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "CalloutMobile",
    href: "/mobile/callout",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile callout component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "StatusLabelMobile",
    href: "/mobile/status-label",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile status label component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "TagChipMobile",
    href: "/mobile/tag-chip",
    section: "Mobile UI",
    type: "mobile" as const,
    description: "Mobile tag chip component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "TextMobile",
    href: "/mobile/text",
    section: "Mobile Typography",
    type: "mobile" as const,
    description: "Mobile text component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "HeadingMobile",
    href: "/mobile/heading",
    section: "Mobile Typography",
    type: "mobile" as const,
    description: "Mobile heading component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "AppShellMobile",
    href: "/mobile/app-shell",
    section: "Mobile Layout",
    type: "mobile" as const,
    description: "Mobile app shell layout component from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "ScreenMobile",
    href: "/mobile/screen",
    section: "Mobile Layout",
    type: "mobile" as const,
    description: "Mobile screen layout wrapper from ui-mobile",
    addedAt: "2026-03-07",
  },
  {
    label: "CardMobile",
    href: "/mobile/card",
    section: "Mobile Containers",
    type: "mobile" as const,
    description: "Mobile card container component from ui-mobile",
    addedAt: "2026-03-07",
  }
];

export function isNewComponent(comp: ComponentData, windowDays = 30): boolean {
  if (!comp.addedAt) return false;
  const diff = Date.now() - new Date(comp.addedAt).getTime();
  return diff >= 0 && diff <= windowDays * 86_400_000;
}

export function searchComponents(
  query: string,
  filterType?: "web" | "mobile"
): ComponentData[] {
  const q = query.toLowerCase().trim();

  if (!q) return [];

  return componentsData.filter((comp) => {
    const matchesQuery =
      comp.label.toLowerCase().includes(q) ||
      comp.section.toLowerCase().includes(q) ||
      comp.description.toLowerCase().includes(q);

    const matchesType = !filterType || comp.type === filterType;

    return matchesQuery && matchesType;
  });
}
